openapi: 3.2.0
info:
  version: '1'
  title: MOVEit Transfer REST Reports API
  x-swagger-net-version: 8.5.28.001
  x-logo:
    url: images/MOVEitLogo.svg
  description: '**Release 2025.1**, **version 17.01**


    *MOVEit securely collects, stores, manages, and distributes information within organizations, between businesses, and more...*


    > **Important!**

    The REST API is an optionally licensed feature that runs at the MOVEit Transfer Server.'
servers:
- url: https://127.0.0.1
tags:
- name: Reports
paths:
  /api/v1/reports/{Id}/results/download:
    get:
      tags:
      - Reports
      summary: Download report run result
      operationId: GETapi/v1/reports/{Id}/results/download?Format={Format}-1.0
      parameters:
      - name: Id
        in: path
        description: Report Id
        required: true
        schema:
          type: string
      - name: format
        in: query
        description: Report output format. If value is null, the default report format is used.
        required: false
        schema:
          type: string
          enum:
          - XML
          - CSV
          - HTMLNAKED
          - HTMLSTYLED
          - Unknown
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
            text/json:
              schema:
                type: object
            application/problem+json:
              schema:
                type: object
        '403':
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorModel'
            text/json:
              schema:
                $ref: '#/components/schemas/ErrorModel'
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ErrorModel'
        '500':
          description: Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorModel'
            text/json:
              schema:
                $ref: '#/components/schemas/ErrorModel'
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ErrorModel'
      security:
      - Authorization: []
  /api/v1/reports:
    get:
      tags:
      - Reports
      summary: Get all reports current user can view
      operationId: GETapi/v1/reports?Page={Page}&PerPage={PerPage}&SortField={SortField}&SortDirection={SortDirection}-1.0
      parameters:
      - name: page
        in: query
        description: Page number to display
        required: false
        schema:
          type: integer
          format: int32
      - name: perPage
        in: query
        description: Items per page in result collection; Default is 25
        required: false
        schema:
          type: integer
          format: int32
      - name: sortField
        in: query
        description: Name of field to sort the results by. (title); Default is title.
        required: false
        schema:
          type: string
      - name: sortDirection
        in: query
        description: Sort direction; Default is ascending.
        required: false
        schema:
          type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PagedModelOfSimpleReportModel'
            text/json:
              schema:
                $ref: '#/components/schemas/PagedModelOfSimpleReportModel'
            application/problem+json:
              schema:
                $ref: '#/components/schemas/PagedModelOfSimpleReportModel'
        '403':
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorModel'
            text/json:
              schema:
                $ref: '#/components/schemas/ErrorModel'
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ErrorModel'
        '500':
          description: Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorModel'
            text/json:
              schema:
                $ref: '#/components/schemas/ErrorModel'
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ErrorModel'
      security:
      - Authorization: []
  /api/v1/reports/import:
    post:
      tags:
      - Reports
      summary: Create new custom report from file
      description: The content type of the request must be "multipart/form-data".
      operationId: POSTapi/v1/reports/import-1.0
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ReportDetailedModel'
            text/json:
              schema:
                $ref: '#/components/schemas/ReportDetailedModel'
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ReportDetailedModel'
        '403':
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorModel'
            text/json:
              schema:
                $ref: '#/components/schemas/ErrorModel'
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ErrorModel'
        '422':
          description: Invalid Request Parameters
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UnprocessableEntityErrorModel'
            text/json:
              schema:
                $ref: '#/components/schemas/UnprocessableEntityErrorModel'
            application/problem+json:
              schema:
                $ref: '#/components/schemas/UnprocessableEntityErrorModel'
        '500':
          description: Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorModel'
            text/json:
              schema:
                $ref: '#/components/schemas/ErrorModel'
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ErrorModel'
      security:
      - Authorization: []
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                file:
                  type: string
                  description: Report xml file
                  format: binary
              required:
              - file
components:
  schemas:
    UnprocessableEntityErrorModel:
      description: Represents an error returned by API in case of HTTP 422 error
      properties:
        errors:
          description: Detailed information about errors in provided parameters
          items:
            $ref: '#/components/schemas/FieldErrorModel'
          readOnly: true
          xml:
            name: FieldErrorModel
            wrapped: true
          type: array
        detail:
          description: An explanation specific to this occurrence of the error
          type: string
        errorCode:
          description: An error number, defined by the application
          type: integer
          format: int32
          default: 0
        title:
          description: Short summary of the error type
          type: string
      xml:
        name: UnprocessableEntityErrorModel
      type: object
    PagedModelOfSimpleReportModel:
      description: Represents paged response object with proper navigations
      properties:
        items:
          description: Items on the given page
          items:
            $ref: '#/components/schemas/SimpleReportModel'
          readOnly: true
          xml:
            name: SimpleReportModel
            wrapped: true
          type: array
        paging:
          $ref: '#/components/schemas/PagingInfoModel'
          description: Paging data for given response
        sorting:
          description: Sorting data for given response
          items:
            $ref: '#/components/schemas/SortFieldDto'
          xml:
            name: SortFieldDto
            wrapped: true
          type: array
      xml:
        name: PagedModel`1
      type: object
    SortFieldDto:
      properties:
        sortField:
          type: string
        sortDirection:
          type: string
          enum:
          - asc
          - desc
      xml:
        name: SortFieldDto
      type: object
    FieldErrorModel:
      description: Describes error in particular parameter of the request
      properties:
        field:
          description: Name of the field that's invalid
          type: string
        rejected:
          description: Value of the field that's invalid
          type: string
        message:
          description: Explanation of the error
          type: string
      xml:
        name: FieldErrorModel
      type: object
    SimpleReportModel:
      description: Simple report model.
      properties:
        id:
          description: Report Id.
          type: integer
          format: int32
        title:
          description: Report name.
          type: string
        category:
          description: Report category.
          type: string
          enum:
          - FileTransfer
          - AdHocTransfer
          - Storage
          - UserMaintenance
          - UserStatus
          - Security
          - Performance
          - ContentScanning
          - System
          - Custom
          - Default
          - Unknown
      xml:
        name: SimpleReportModel
      type: object
    PagingInfoModel:
      description: Information about paging for collection response
      properties:
        page:
          description: Current page in collection
          type: integer
          format: int32
        perPage:
          description: Items per page
          type: integer
          format: int32
        totalItems:
          description: Total items in collection
          type: integer
          format: int64
        totalPages:
          description: Total number of pages in collection
          readOnly: true
          type: integer
          format: int32
      xml:
        name: PagingInfoModel
      type: object
    ErrorModel:
      description: Represents an error returned by API
      properties:
        detail:
          description: An explanation specific to this occurrence of the error
          type: string
        errorCode:
          description: An error number, defined by the application
          type: integer
          format: int32
          default: 0
        title:
          description: Short summary of the error type
          type: string
      xml:
        name: ErrorModel
      type: object
    ReportDetailedModel:
      description: Report detailed model.
      properties:
        orgId:
          description: Organization Id.
          type: integer
          format: int32
        createStamp:
          description: Creation date/time.
          type: string
        createUsername:
          description: Creator username.
          type: string
        lastChangeStamp:
          description: Last change stamp.
          type: string
        type:
          description: Report type.
          type: string
          enum:
          - AdHocTransferByDay
          - AdHocTransferByDayByGroup
          - AdHocTransferByDayByUser
          - AdHocTransferByGroup
          - AdHocTransferByMonth
          - AdHocTransferByMonthByGroup
          - AdHocTransferByMonthByUser
          - AdHocTransferByUser
          - AdHocTransferByWeek
          - AdHocTransferByWeekByGroup
          - AdHocTransferByWeekByUser
          - AdHocTransferTotal
          - AdHocTransferUserSnapshot
          - ContentScanningDLPViolations
          - ContentScanningMaintenanceByActivity
          - ContentScanningMaintenanceByActivityByDay
          - ContentScanningMaintenanceByActivityByMonth
          - ContentScanningMaintenanceByActivityByWeek
          - ContentScanningMaintenanceByDay
          - ContentScanningMaintenanceByMonth
          - ContentScanningMaintenanceByWeek
          - ContentScanningMaintenanceTotal
          - ContentScanningViolations
          - FileTransferByDay
          - FileTransferByGroup
          - FileTransferByGroupByDay
          - FileTransferByGroupByMonth
          - FileTransferByGroupByWeek
          - FileTransferByIP
          - FileTransferByIPByDay
          - FileTransferByIPByMonth
          - FileTransferByIPByWeek
          - FileTransferByInterface
          - FileTransferByInterfaceByDay
          - FileTransferByInterfaceByMonth
          - FileTransferByInterfaceByWeek
          - FileTransferByMonth
          - FileTransferByUser
          - FileTransferByUserByDay
          - FileTransferByUserByMonth
          - FileTransferByUserByWeek
          - FileTransferByWeek
          - FileTransferTotal
          - PerformanceCPUAll
          - PerformanceCPUByDay
          - PerformanceCPUByHour
          - PerformanceDiskAll
          - PerformanceDiskByDay
          - PerformanceDiskByHour
          - PerformanceHandlesAll
          - PerformanceHandlesByDay
          - PerformanceHandlesByHour
          - PerformanceMemUsageAll
          - PerformanceMemUsageByDay
          - PerformanceMemUsageByHour
          - PerformanceProcessesAll
          - PerformanceProcessesByDay
          - PerformanceProcessesByHour
          - PerformanceSessionsAll
          - PerformanceSessionsByDay
          - PerformanceSessionsByHour
          - PerformanceSummaryAll
          - PerformanceSummaryByDay
          - PerformanceSummaryByHour
          - PerformanceThreadsAll
          - PerformanceThreadsByDay
          - PerformanceThreadsByHour
          - PerformanceVMSizeAll
          - PerformanceVMSizeByDay
          - PerformanceVMSizeByHour
          - SecurityLockedOutIPsCurrent
          - SecurityLockedOutIPsHistorical
          - SecurityLockedOutUsersCurrent
          - SecurityLockedOutUsersHistorical
          - SecuritySuspiciousIPsManyAttempts
          - SecuritySuspiciousIPsManyUsernames
          - SecuritySuspiciousUsernamesManyAttempts
          - SecuritySuspiciousUsernamesManyIPs
          - SecurityWhitelistedIPs
          - StorageByAge
          - StorageByAgeIncludingSubFolders
          - StorageByFolder
          - StorageByFolderIncludingSubFolders
          - StorageByGroup
          - StorageByUser
          - StorageTotal
          - SystemOrgKeyRotations
          - SystemOrgKeys
          - UserMaintenanceByActivity
          - UserMaintenanceByActivityByDay
          - UserMaintenanceByActivityByMonth
          - UserMaintenanceByActivityByWeek
          - UserMaintenanceByDay
          - UserMaintenanceByMonth
          - UserMaintenanceByWeek
          - UserMaintenanceTotal
          - UserStatusActiveUsers
          - UserStatusAddressBooks
          - UserStatusDefaultHomeFolderPermissions
          - UserStatusFolderPermissions
          - UserStatusFolderQuotaAny
          - UserStatusFolderQuotaDefined
          - UserStatusFolderQuotaNearAbove
          - UserStatusGroupMembership
          - UserStatusGroupSummary
          - UserStatusInactiveUsers
          - UserStatusPackageQuotaAny
          - UserStatusPackageQuotaDefined
          - UserStatusPackageQuotaNearAbove
          - UserStatusPasswordAboutToExpire
          - UserStatusSignOnNoticeAccepted
          - UserStatusUserListForAuditors
          - CustomCustom
          - DefaultDefault
          - Unknown
        outputFormat:
          description: Report output format.
          type: string
          enum:
          - XML
          - CSV
          - HTMLNAKED
          - HTMLSTYLED
          - Unknown
        showQuery:
          description: True if show query.
          type: boolean
        csvDelimiter:
          description: Delimiter.
          type: string
        csvQuoteMark:
          description: Quote char.
          type: string
        csvEscapeFormulaPrefix:
          description: Escape formula prefix.
          type: integer
          format: int32
        schedule:
          description: Schedule.
          type: string
        saveInFolder:
          description: Folder path to save in.
          type: string
        saveAsFile:
          description: Save as file.
          type: string
        overwriteExistingFile:
          description: True if overwrite existing file.
          type: boolean
        optionStartDate:
          description: Report option start date.
          type: string
        optionEndDate:
          description: Report option end date.
          type: string
        optionSizeUnits:
          description: Report size unit.
          type: string
          enum:
          - KB
          - MB
          - GB
          - Unknown
        optionAttemptThreshold:
          description: Attempt threshold.
          type: integer
          format: int32
        optionIPThreshold:
          description: IP threshold.
          type: integer
          format: int32
        optionUsernameThreshold:
          description: Username threshold.
          type: integer
          format: int32
        customFields:
          description: Custom fields.
          type: string
        customTables:
          description: Custom tables.
          type: string
        customCriteria:
          description: Custom criteria.
          type: string
        customGrouping:
          description: Custom grouping.
          type: string
        customOrder:
          description: Custom order.
          type: string
        customLimit:
          description: Custom limit.
          type: string
        id:
          description: Report Id.
          type: integer
          format: int32
        title:
          description: Report name.
          type: string
        category:
          description: Report category.
          type: string
          enum:
          - FileTransfer
          - AdHocTransfer
          - Storage
          - UserMaintenance
          - UserStatus
          - Security
          - Performance
          - ContentScanning
          - System
          - Custom
          - Default
          - Unknown
      xml:
        name: ReportDetailedModel
      type: object
  securitySchemes:
    Authorization:
      type: apiKey
      description: 'Transfer API token. Put token value obtained using following format: "Bearer {token}"'
      name: Authorization
      in: header
